function DynamicBC_Cluster_beta()
D.fig = figure('Name','Cluster analysis',...       
    'units','normalized',...      
    'menubar','none',...       
    'numbertitle','off',...      
    'unit','normalized',...
    'color',[0.95 0.95 0.95],...
    'position',[0.25 0.2 0.4 0.4]);
movegui(D.fig,'center');           
            
%% Condition for the cluster: 1 map 2 matrix
%% 1 map  
% rd_mr might use other for instead?
D_bg_mr_pos = [0.01 0.7 0.66 0.25];
D.D_bg_mr_pos = D_bg_mr_pos;

D.ed_files = uicontrol('style','text',...
                    'visible','off',...
                    'string',' ');
                
D.bg_mr(1) = uibuttongroup('units','norm',...
                     'pos',D_bg_mr_pos);   
                 
D.tx_mr(1) = uicontrol(D.bg_mr(1),...
                'style','text',...
                'units','norm',...
                'position',[0.2 0.92 0.6 0.26],...
                'string','Select Modules',...               
                'fontunits', 'normalized', 'fontsize',0.8,...
                'fontweight','bold',...
                'foregroundcolor',[.1 .1 .1]);     

D.rd_mr(1) = uicontrol('Parent',D.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.05 0.65 0.7 0.3],...
                    'string','Image Type',...                    
                    'backgroundc',get(D.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');  
D.tx_mask = uicontrol('Parent',D.bg_mr(1),...
                'style','text',...
                'units','norm',...
                'position',[0.05 0.25 0.8 0.33],...
                'string','Mask files',...
                'backgroundc',get(D.bg_mr(1),'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.4,...
                'fontweight','bold',...
                'horizontalalign','left',...
                'foregroundcolor',[0 0 0.8]);
D.ed_mask = uicontrol('Parent',D.bg_mr(1),...
                        'style','edit',...
                        'unit','norm',...
                        'position',[0.25 0.38 0.6 0.22],...
                        'fontunits', 'normalized', 'fontsize',0.5,...
                        'string','not selected');  
D.ed_maskselect = uicontrol('Parent',D.bg_mr(1),...
                            'style','pushbutton',...
                            'units','norm',...
                            'position',[0.88 0.37 0.09 0.25],...
                            'string','...',...
                            'TooltipString','Click me!',...
                            'fontunits', 'normalized', 'fontsize',0.8);                    
%% matrix
D.rd_mr(2) = uicontrol('Parent',D.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.05 0.05 0.5 0.3],...
                    'string','Matrix type',...                    
                    'backgroundc',get(D.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','e.g. FC(I,J)');                 

                
D.tx_varname = uicontrol('Parent',D.bg_mr(1),...
                    'style','text',...
                    'units','norm',...
                    'position',[0.45 0.001 0.3 0.25],...
                    'string','Variable name:',...                    
                    'backgroundc',get(D.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.45,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'visible','off',...
                    'TooltipString','e.g. FC(I,J)');                 
D.ed_varname = uicontrol('Parent',D.bg_mr(1),...
                    'style','edit',...
                    'units','norm',...
                    'position',[0.75 0.03 0.2 0.25],...
                    'string','FCM.Matrix',...                    
                    'backgroundc',get(D.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...                   
                    'visible','off',...
                    'TooltipString','...'); 

D.tx_fs = uicontrol('Parent',D.bg_mr(1),...
                    'style','text',...
                    'units','norm',...
                    'position',[0.58 0.68 0.3 0.2],...
                    'string','Module number:',...                    
                    'backgroundc',get(D.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.6,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[1 0 0],...
                    'value',1,...
                    'TooltipString','...');
D.ed_fs = uicontrol('Parent',D.bg_mr(1),...
                    'style','edit',...
                    'units','norm',...
                    'position',[0.85 0.7 0.13 0.2],...
                    'string','6',...                    
                    'backgroundc',get(D.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[1 0 0],...                   
                    'visible','on',...
                    'TooltipString','...');          
                        


%% data selection
D.bg_data = uibuttongroup('Parent',D.fig,...
                     'units','norm',...
                     'pos',[0.01 0.59 0.98 0.1]); 
D.data_tx = uicontrol('Parent',D.bg_data,...
                    'style','text',...
                    'units','norm',...
                    'position',[0.001 0.01 0.2 0.7],...
                    'string','Select Data:',...                    
                    'backgroundc',get(D.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');    
D.ed_data = uicontrol(D.bg_data,...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.18 0.15 0.6 0.7],...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'string','not selected');    
              
D.pb_data = uicontrol(D.bg_data,...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.78 0.15 0.05 0.7],...
                  'string','...',...
                  'TooltipString','Click me!',...
                  'fontunits', 'normalized', 'fontsize',0.8);     

%% OutputDirectory
D.bg_data2 = uibuttongroup('Parent',D.fig,...
                     'units','norm',...
                     'pos',[0.01 0.49 0.98 0.1]); 
D.data_tx2 = uicontrol('Parent',D.bg_data2,...
                    'style','text',...
                    'units','norm',...
                    'position',[0.001 0.01 0.2 0.7],...
                    'string','Select OutDir:',...                    
                    'backgroundc',get(D.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');    
D.ed_data2 = uicontrol(D.bg_data2,...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.18 0.15 0.6 0.7],...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'string','not selected');    
              
D.pb_output2 = uicontrol(D.bg_data2,...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.78 0.15 0.05 0.7],...
                  'string','...',...
                  'TooltipString','Click me!',...
                  'fontunits', 'normalized', 'fontsize',0.8); 
              
D.pb_run = uicontrol(D.bg_data2,...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.85 0.08 0.12 0.8],...
                  'string','Run',...
                  'TooltipString','Click me!',...
                  'fontunits', 'normalized', 'fontsize',0.6); 
%% Cluster methods selection

D.ClusterMethod = uibuttongroup('Parent',D.fig,...
                     'units','norm',...
                     'pos',[0.69 0.7 0.30 0.25]);   
D.CMe(1) = uicontrol('Parent',D.ClusterMethod,...
                'style','rad',...
                'units','norm',...
                'position',[0.2 0.75 0.6 0.2],...
                'string','Correlation',...               
                'fontunits', 'normalized', 'fontsize',0.6,...
                'fontweight','bold',...
                'foregroundcolor',[.1 .1 .1],...
                'value',1); 
D.CMe(2) = uicontrol('Parent',D.ClusterMethod,...
                'style','rad',...
                'units','norm',...
                'position',[0.2 0.25 0.6 0.2],...
                'string','sqEuclidean',...               
                'fontunits', 'normalized', 'fontsize',0.6,...
                'fontweight','bold',...
                'foregroundcolor',[.1 .1 .1],...
                'value',0); 
%% Show the module


%%

% set(D.CMe(1:2),'callback',{@wgr_methods_select,D});
set(D.ed_maskselect,'callback',{@wgr_select_dir_rewrite,D,'mask',''});
set(D.pb_data,'callback',{@wgr_select_dir_rewrite,D,'data',''});
set(D.pb_output2,'callback',{@wgr_select_dir_rewrite,D,'output',''});
set(D.rd_mr(1:2),'callback',{@wgr_sphere_ROI_call_writes,D});
set(D.pb_run,'callback',{@wgr_run_call,D});


function []=wgr_run_call(varargin)
D = varargin{3};  % Get structure.
flag_datatype = cell2mat(get(D.rd_mr,'val'));
% flag_seed_ROI = cell2mat(get(D.rd_mr,'val'));
Datafold = get(D.ed_data,'string');
SubFold = dir(Datafold);
outputd = get(D.ed_data2,'string');
k = str2num(get(D.ed_fs,'string'));  % cluster number
methods = cell2mat(get(D.CMe,'val'));
if methods(1)
    CluMet = 'correlation';
else
    CluMet = 'sqEuclidean';
end
% save D D
if flag_datatype(1)
    maskfile = get(D.ed_mask,'string');
    [IDX_subj,IDX_subjre]=dynamicBC_clustermaps_beta(k,outputd,maskfile,Datafold,CluMet);
%     save('IDX_SUBJ2','IDX_subj','IDX_subjre')
elseif flag_datatype(2)
    matname = get(D.ed_varname,'string');
    [IDX_subj,IDX_subjre]=dynamicBC_clustermatrix_beta(k,outputd,matname,Datafold,CluMet);
%     save('IDX_SUBJ2','IDX_subj','IDX_subjre')
%     dynamicBC_clustermatrix(k,outputd,matname,subjdir)
end
% 0.01 0.49 0.98 0.1
% 0.01 0.59 0.98 0.1
% 
D.showmod1 = axes('parent',D.fig,'pos',[0.1,0.05,0.8,0.15]);
imagesc(IDX_subj)
title(D.showmod1,'Module clusters')
axis off
D.showmod2 = axes('parent',D.fig,'pos',[0.1,0.25,0.8,0.15]);
imagesc(IDX_subjre)
title(D.showmod2,'Module clusters rebuild')
axis off

fprintf('We have done!  =_= \n')
% close(D.fig);




function [] = wgr_select_dir_rewrite(varargin)
D = varargin{3};
str = varargin{4};
if strcmp(str,'mask')
    files = spm_select(1,'image','maskfile');
else
    files = spm_select(1,'dir','file folds');
end
% files = spm_select(inf,'any');

if strcmp(str ,'mask')
%     set(D.ed_maskselect,'string',files);
    set(D.ed_mask,'string',files);
elseif strcmp(str ,'data')
    set(D.ed_data,'string',files);
elseif strcmp(str,'output')
    set(D.ed_data2,'string',files);
end


% function []=wgr_methods_select(varargin)
% D = varargin{3};  % Get structure.
% flag_methods = cell2mat(get(D.CMe,'val'));
% if flag_methods(1)
%     set([D.tx_mask(:),D.ed_mask(:),D.ed_maskselect(:)],'enable','on');   
%     set([D.ed_varname,D.tx_varname],'vis','off');
% elseif flag_methods(2)
%    set([D.tx_mask(:),D.ed_mask(:),D.ed_maskselect(:)],'enable','off');
%    set([D.ed_varname,D.tx_varname],'vis','on');
% % else
% %     set([D.ed_MNI(:),D.tx_MNI(:)],'enable','off');
% %     set([D.ed_varname,D.tx_varname],'vis','on');
% end

function []=wgr_sphere_ROI_call_writes(varargin)
D = varargin{3};  % Get structure.
flag_seed_mask = cell2mat(get(D.rd_mr,'val'));
if flag_seed_mask(1)
    set([D.tx_mask(:),D.ed_mask(:),D.ed_maskselect(:)],'enable','on');   
    set([D.ed_varname,D.tx_varname],'vis','off');
elseif flag_seed_mask(2)
   set([D.tx_mask(:),D.ed_mask(:),D.ed_maskselect(:)],'enable','off');
   set([D.ed_varname,D.tx_varname],'vis','on');
% else
%     set([D.ed_MNI(:),D.tx_MNI(:)],'enable','off');
%     set([D.ed_varname,D.tx_varname],'vis','on');
end