function DynamicBC
S.fig = figure('Visible','on',...
    'numbertitle','off',...
    'menubar','none',...              'units','normalized',...
    'color','w',...
    'position',[563    98   480   360],...[0.4   0.4    0.309    0.5],...
    'name',['DynamicBC Version 2.2(',getenv('USERNAME'),')'],...
    'resize','off');

[imdat map] = imread('DBC.jpg');
% CDdat1 = imdat(169:434,230:476,:);
% CDdat2 = imdat(169:434,482:727,:);
% CDdat3 = imdat(439:704,230:476,:);
% CDdat4 = imdat(439:704,482:727,:);

S.pb(1) = uicontrol('parent',S.fig,...
    'unit','norm',...
    'pos',[235/960,(720-225)/720,(472-235)/960,50/720],...
    'style','pushbutton',...
    'string','Functional Conn',...
     'backgroundc','k',...
     'foregroundcolor',[1 1 0],...
     'fontname','Calibri',...'fontname','Segoe Script',...
     'fontunits', 'normalized',... 
     'fontweight','bold');
%     'backgroundcolor','k',...
%     'CData',);
S.pb(2) = uicontrol('parent',S.fig,...
    'unit','norm',...
    'pos',[486/960,(720-225)/720,(724-486)/960,50/720],...
    'style','pushbutton',...
    'string','Effective Conn',...
     'backgroundc','k',...
     'foregroundcolor',[1 1 0],...
     'fontname','Calibri',...'fontname','Segoe Script',...
     'fontunits', 'normalized',... 
     'fontweight','bold');
%     'backgroundcolor','k',...
S.pb(3) = uicontrol('parent',S.fig,...
    'unit','norm',...
    'pos',[235/960,(720-495)/720,(472-235)/960,50/720],...
    'style','pushbutton',...
    'string','Functional Ampl',...
     'backgroundc','k',...
     'foregroundcolor',[1 1 0],...
     'fontname','Calibri',...'fontname','Segoe Script',...
     'fontunits', 'normalized',... 
     'fontweight','bold');
%     'backgroundcolor','k',...
S.pb(4) = uicontrol('parent',S.fig,...
    'unit','norm',...
    'pos',[486/960,(720-495)/720,(724-486)/960,50/720],...
    'style','popupmenu',...
    'string',{'Tools/Batch','Clustering','Spectrum','Visualization','Quit'},...
     'backgroundc','k',...
     'foregroundcolor',[1 1 0],...
     'fontname','Calibri',...'fontname','Segoe Script',...
     'fontunits', 'normalized',... 
     'fontweight','bold');
%     'backgroundcolor','k',...
haxes = axes('parent',S.fig,...
    'unit','norm',...
    'pos',[0 0 1 1]);
imshow(imdat, map, 'Parent',haxes)
movegui(S.fig,'center');
% Make the GUI visible.
set(S.fig,'Visible','on');

set(S.pb(1:4),{'callback'},{{@pb_call,S}});
end



function [E] = pb_call(varargin)
% Callback for togglebuttons.
S = varargin{3};  % Get the structure.
%%==============================================================
E.S = S;
fc = get(S.pb(1),'val');
ec = get(S.pb(2),'val');
dalff = get(S.pb(3),'val');
clu_spe = get(S.pb(4),'val');

if ec
    disp('Dynamic Effective Connectivity---setting');
elseif fc
    disp('Dynamic Functional Connectivity---setting'); 
elseif dalff
    disp('Dynamic Amplitude---setting');
    movegui(S.fig,'west');
    DynamicBC_dALFF_main;
    return
elseif clu_spe
    str_utilis = get(S.pb(4),'string');
    switch str_utilis{clu_spe};
        case 'Spectrum'
            DynamicBC_SpectrumGUI;
        case  'Clustering'
            DynamicBC_Cluster;
        case 'Visualization'
            DynamicBC_CONGRAMGUI;
        case 'Quit'
            delete(S.fig);
    end
    return
end
E.fc_ec = [fc ec];
movegui(S.fig,'west');

E.fig = figure('Name','Parameter Setup',...       'units','normalized',...
       'menubar','none',...
       'numbertitle','off',...       
       'position',get(S.fig,'pos')*1.5);

movegui(E.fig,'center');
   
%%=============================Configurations=================================
E_bg_title_pos = [0.01 0.9 0.985 0.096];
E.bg_title(1) = uibuttongroup('units','norm',...
                     'pos',E_bg_title_pos);  
E.tx_title(1) = uicontrol(E.bg_title(1),...
                'style','text',...
                'units','normalized',...
                'position',[0.05 0.1 0.9 0.8],...         
                'string','Configurations',...
                'backgroundc',get(E.bg_title(1),'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.75,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .8]);
if ec
    set(E.tx_title(1),'string','Configurations (EC)') ;
elseif fc
    set(E.tx_title(1),'string','Configurations (FC)') ;
end            
%%===========================Time-Varying Model===================================
E_bg_tvmodel_pos = [0.535 0.56 0.46 0.32];
E.bg_tvmodel_pos = E_bg_tvmodel_pos;
E.bg_tvmodel(1) = uibuttongroup('Parent',E.fig,...
    'Title','Time-Varying Model','fontunits', 'normalized', 'fontsize',0.1,'foregroundcolor',[.8 .1 .1],...
                     'units','normalized',... 
                     'pos',E_bg_tvmodel_pos);   
                 
E.rd_tvmodel(1) = uicontrol('Parent',E.bg_tvmodel(1),...
                    'style','rad',...
                    'units','normalized',...
                    'position',[0.1 0.5 0.8 0.45],...
                    'string',' Sliding-window',...                    
                    'backgroundc',get(E.bg_title(1),'backgroundc'),...                    
                    'fontweight','bold',...                
                    'fontunits', 'normalized', 'fontsize',0.25,...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','Sliding-window Analysis');  
E.rd_tvmodel(2) = uicontrol('Parent',E.bg_tvmodel(1),...
                    'style','rad',...
                    'units','normalized',...
                    'position',[0.1 0.1 0.8 0.45],...
                    'string','   FLS',...                    
                    'backgroundc',get(E.bg_title(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.25,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','Flexible Least Square Analysis');     


pos_rd11 = [0.01 0.37 0.4 0.22;
            0.015 0.03 0.3 0.25;
            0.48 0.03 0.35 0.25;
            0.55 0.43 0.35 0.18;
            0.3 0.1 0.15 0.2
            0.85 0.1 0.14 0.2
            ];
str_rd11 ={'Window Size:','Overlap:','(GC)Order:','50','0.6','1'};       
for i=1:3
    E.tx_rd11_tvmodel(i) = uicontrol(E.bg_tvmodel(1),...
                    'style','text',...
                    'units','normalized',...
                    'position',pos_rd11(i,:),...
                    'string',str_rd11{i},...                
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'visible','on',...
                    'foregroundcolor',[.8 .1 .1]);   
    E.ed_rd11_tvmodel(i) = uicontrol(E.bg_tvmodel(1),...
                        'style','edit',...
                        'unit','norm',...
                        'position',pos_rd11(i+3,:),...
                        'fontunits', 'normalized', 'fontsize',0.45,...
                        'string',str_rd11{i+3});   
end
                
%%=====================SLW-FLS parameter=========================================
%% 
E_bg_slw_fls_pos = [0.535 0.35 0.46 0.2];
E.bg_slw_fls_pos = E_bg_slw_fls_pos;
E.bg_slw_fls(1) = uibuttongroup('units','norm',...
    'Title','FLS Parameter','fontunits', 'normalized', 'fontsize',0.16,'foregroundcolor',[.8 .1 .1],...
                     'pos',E_bg_slw_fls_pos);   %Time Alignment
                 
E.rd_slw(1) = uicontrol('Parent',E.bg_slw_fls(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.01 0.55 0.8 0.45],...
                    'string',' Ahead',...                    
                    'backgroundc',get(E.bg_slw_fls(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');  
E.rd_slw(2) = uicontrol('Parent',E.bg_slw_fls(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.4 0.55 0.5 0.45],...
                    'string','  Middle',...                    
                    'backgroundc',get(E.bg_slw_fls(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');     
E.bg_slw_conn(1) = uibuttongroup('Parent',E.bg_slw_fls(1),...
        'Title','Connectivity p-value','fontunits', 'normalized', 'fontsize',0.3,'foregroundcolor',[.8 .1 .1],...
                     'units','norm',...
                     'pos',[0.01 0.01 0.98 0.6]);                  
E.rd_slw_conn(1) = uicontrol('Parent',E.bg_slw_conn(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.01 0.1 0.5 0.8],...
                    'string','FWE',...                    
                    'backgroundc',get(E.bg_slw_conn(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.6,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');  
E.rd_slw_conn(2) = uicontrol('Parent',E.bg_slw_conn(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.3 0.1 0.5 0.8],...
                    'string','Fixed',...                    
                    'backgroundc',get(E.bg_slw_conn(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.6,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');   
E.ed_slw_pvalue = uicontrol('Parent',E.bg_slw_conn(1),...
                    'style','edit',...
                    'units','norm',...
                    'position',[0.64 0.1 0.35 0.8],...
                    'string','0.001',...                    
                    'backgroundc',get(E.bg_slw_conn(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.7,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');                  
E.rd_fls_snr(1) = uicontrol('Parent',E.bg_slw_fls(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.1 0.5 0.8 0.45],...
                    'string','   Default',...                    
                    'backgroundc',get(E.bg_slw_fls(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.39,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');  
E.rd_fls_snr(2) = uicontrol('Parent',E.bg_slw_fls(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.1 0.1 0.8 0.45],...
                    'string','   Fixed',...                    
                    'backgroundc',get(E.bg_slw_fls(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');     
                
E.tx_fls_snr(1) = uicontrol(E.bg_slw_fls(1),...
                    'style','text',...
                    'unit','norm',...
                    'position',[0.5 0.53 0.3 0.32],...
                    'fontunits', 'normalized', 'fontsize',0.55,...
                    'visible','off',...
                    'string','100');                 

E.tx_fls_snr(2) = uicontrol(E.bg_slw_fls(1),...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.5 0.15 0.3 0.32],...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'visible','on',...
                    'string','100'); 
                 

%%===========================ROI-voxel wise===================================
E_bg_rvw_pos = [0.01 0.56 0.50 0.32];
E.bg_rvw = uibuttongroup('Parent',E.fig,...
                    'Title','Set ROI','fontunits', 'normalized', 'fontsize',0.1,'foregroundcolor',[.8 .1 .1],...
                     'units','norm',...
                     'pos',E_bg_rvw_pos);   
rvw_pos =[0.08 0.7 0.5 0.2;
          0.08 0.4 0.5 0.2;
          0.08 0.05 0.5 0.2;];

rvw_str = {'Voxel wise','ROI wise','FCD'};
rvw_val = [1 0 0];
for i=1:3
    E.rd_rvw(i) = uicontrol('Parent',E.bg_rvw,...
                'style','rad',...
                'units','norm',...
                'position',rvw_pos(i,:),...
                'string',rvw_str{i},...                    
                'backgroundc',get(E.bg_rvw,'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.55,...
                'fontweight','bold',...
                'foregroundcolor',[0 0 .8],...
                'value',rvw_val(i));  
end

%% seed MNI-ROI
E.bg_seed_ROI = uibuttongroup('Parent',E.bg_rvw,...                   
                     'units','norm',...
                     'pos',[0.58 0.67 0.42 0.33]);   
seed_ROI_str = {'ROI-Mask','Seed(MNI)'};
seed_ROI_pos = [0.15 0.5 0.8 0.48;
                0.15 0.05 0.8 0.48];
for i=1:2
    E.rd_seed_ROI(i) = uicontrol(E.bg_seed_ROI,...
                    'style','rad',...
                    'units','norm',...
                    'position',seed_ROI_pos(i,:),...
                    'string',seed_ROI_str{i},...                
                    'fontunits', 'normalized', 'fontsize',0.6,...
                    'fontweight','bold',...
                    'val',1,...
                    'enable','on',...
                    'foregroundcolor',[.8 .1 .1]); 
end
           
%% seed MNI input
E.bg_seed_voxel = uibuttongroup('Parent',E.bg_rvw,...
                     'units','norm',...
                     'pos',[0.58 0.01 0.42 0.65]);   

xyz_height = [0.75 0.5 0.26 0.01];  
xyz_label = {'x','y','z','radius'};
xyz_val = {'0','-53','26','6'};
for xyz=1:4       
    E.ed_MNI(xyz) = uicontrol('Parent',E.bg_seed_voxel,...
                        'style','edit',...
                        'units','norm',...
                        'position',[0.4 xyz_height(xyz) 0.58 0.22],...
                        'string',[xyz_val{xyz}],...                    
                        'backgroundc',get(E.bg_slw_conn(1),'backgroundc'),...
                        'fontunits', 'normalized', 'fontsize',0.6,...
                        'fontweight','bold',...
                        'horizontalalign','center',...
                        'foregroundcolor',[0 0 .8],...
                        'value',1,...
                        'TooltipString',[xyz_label{xyz},'-coordinate']); 
    
    E.tx_MNI(xyz) = uicontrol('Parent',E.bg_seed_voxel,...
                        'style','text',...
                        'units','norm',...
                        'position',[0.01 xyz_height(xyz) 0.38 0.22],...
                        'string',[xyz_label{xyz},': = '],...                    
                        'backgroundc',get(E.bg_slw_conn(1),'backgroundc'),...
                        'fontunits', 'normalized', 'fontsize',0.6,...
                        'fontweight','bold',...
                        'horizontalalign','center',...
                        'foregroundcolor',[0 0 .8],...
                        'value',1);  
                    
    if xyz==4
        set(E.ed_MNI(4),'String','6','TooltipString','Sphere radius -mm','position',get(E.ed_MNI(4),'position')+[0.15 0 -0.15 -0.02]);
        set(E.tx_MNI(4),'position',get(E.tx_MNI(4),'position')+[0 -0.01 0.1 0]);
    end                    
end  

            
%%=========================Mask_ROI=====================================
E_bg_mr_pos = [0.01 0.35 0.50 0.2];
E.E_bg_mr_pos = E_bg_mr_pos;

E.ed_mrs_files = uicontrol('style','text',...
                    'visible','off',...
                    'string',' ');
                
E.bg_mr(1) = uibuttongroup('units','norm',...
        'Title','Mask','fontunits', 'normalized', 'fontsize',0.16,'foregroundcolor',[.8 .1 .1],...
                     'pos',E_bg_mr_pos);   
% mapping case.                 
E.rd_mr(1) = uicontrol('Parent',E.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.1 0.5 0.8 0.45],...
                    'string',' Default mask',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.39,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');  
E.rd_mr(2) = uicontrol('Parent',E.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.1 0.1 0.8 0.45],...
                    'string','User-Defined Mask',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');     
% ROI wise case
E.rd_mr(3) = uicontrol('Parent',E.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.01 0.5 0.8 0.45],...
                    'string','Nifti Label',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');  
E.rd_mr(4) = uicontrol('Parent',E.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.6 0.5 0.3 0.45],...
                    'string','TXT',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');   
E.rd_mr(5) = uicontrol('Parent',E.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.01 0.1 0.75 0.45],...
                    'string','Mat,variable name:',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');                   
E.ed_mat = uicontrol('Parent',E.bg_mr(1),...
                    'style','edit',...
                    'units','norm',...
                    'position',[0.65 0.1 0.3 0.4],...
                    'string','data',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','right',...
                    'foregroundcolor',[0 0 .8],...                   
                    'visible','off',...
                    'TooltipString','...');                  
  
% E.tx_mr(1) = uicontrol(E.bg_mr(1),...
%                 'style','text',...
%                 'units','norm',...
%                 'position',[0.2 0.92 0.6 0.26],...
%                 'string','Mask/ROI',...               
%                 'fontunits', 'normalized', 'fontsize',0.8,...
%                 'fontweight','bold',...
%                 'foregroundcolor',[.8 .1 .1]);   
            
set(E.rd_mr(1:2),'visible','on');
set(E.rd_mr(3:5),'visible','off');
set(E.bg_slw_conn,'visible','off');
set(E.rd_slw(:),'visible','off');
  
%%=========================Mask_ROI_selection=====================================

E_bg_mrs_pos = [0.01 0.195 0.986 0.15];
E.bg_mrs(1) = uibuttongroup('parent',E.fig,...     'Title','Mask','fontunits', 'normalized', 'fontsize',0.16,'foregroundcolor',[.8 .1 .1],...
                     'units','norm',...
                     'pos',E_bg_mrs_pos);    
E.tx_mask = uicontrol(E.bg_mrs(1),...
                'style','text',...
                'units','norm',...
                'position',[0.001 0.4 0.3 0.4],...
                'string','Mask/ROI:',...
                'backgroundc',get(E.bg_mrs(1),'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.5,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .8]);
E.ed_mrs = uicontrol(E.bg_mrs(1),...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.28 0.5 0.64 0.4],...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'string','not selected');       
E.pb_mask_dir = uicontrol(E.bg_mrs(1),...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.9 0.5 0.09 0.4],...
                  'string','...',...
                  'TooltipString','Click me!',...
                  'fontunits', 'normalized', 'fontsize',0.8);     
              
E.tx_mrs = uicontrol(E.bg_mrs(1),...
                'style','text',...
                'units','norm',...
                'position',[0.001 0.01 0.3 0.4],...
                'string','Data Directory:',...
                'backgroundc',get(E.bg_mrs(1),'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.5,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .8]);
E.ed_bg_data_dir = uicontrol(E.bg_mrs(1),...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.28 0.05 0.64 0.4],...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'string','not selected');       
E.pb_datadir = uicontrol(E.bg_mrs(1),...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.9 0.05 0.09 0.4],...
                  'string','...',...
                  'TooltipString','Click me!',...
                  'fontunits', 'normalized','fontsize',0.8);       
              
%%========================Out_put Misc======================================
E_bg_misc_pos = [0.01 0.01 0.985 0.18]; 
E.bg_misc(1) = uibuttongroup('parent',E.fig,'units','norm',...
                     'pos',E_bg_misc_pos);  
E.tx_prefix(1) = uicontrol(E.bg_misc(1),...
                'style','text',...
                'units','norm',...
                'position',[0.02 0.5 0.24 0.3],...       
                'string','Prefix(Output):',...            
                'fontunits', 'normalized', 'fontsize',0.55,...
                'fontweight','bold',...
                'visible','on',...
                'foregroundcolor',[.8 .1 .8]);   
E.ed_prefix(1) = uicontrol(E.bg_misc(1),...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.25 0.55 0.19 0.28],...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'string','TV');   
              
E.tx_output_dir(1) = uicontrol(E.bg_misc(1),...
                'style','text',...                
                'unit','normalized',...
                'string','Out Directory:',...
                'position',[0.01 0.1 0.25 0.3],...'position',[0.01 0.01 0.25 0.2],...
                'backgroundc',get(E.bg_misc(1),'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.6,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .8]);
E.ed_bg_dir_out = uicontrol(E.bg_misc(1),...
                    'style','edit',...
                    'unit','normalized',...
                    'position',[0.24 0.1 0.45 0.3],...'position',[0.26 0.01 0.65 0.2],...
                    'fontunits', 'normalized', 'fontsize',0.6,...
                    'string','not selected');       
E.pb_datadir_out = uicontrol(E.bg_misc(1),...
                  'style','pushbutton',...
                  'units','normalized',...
                  'position',[0.69 0.1 0.09 0.32],...'position',[0.91 0.005 0.09 0.25],...
                  'string','...',...
                  'fontunits', 'normalized','fontsize',0.8,...
                  'TooltipString','Click me!');        
% E.tx_par(1) = uicontrol(E.bg_misc(1),...
%                   'style','text',...
%                   'units','norm',...
%                   'position',[0.03 0.32 0.29 0.3],...
%                   'string','Parallel Workers #:',...
%                   'horizontalalign','left',...
%                   'fontunits', 'normalized', 'fontsize',0.6); 
% E.ed_par(1) = uicontrol(E.bg_misc(1),...
%                     'style','edit',...
%                     'unit','norm',...
%                     'position',[0.32 0.35 0.15 0.286],...
%                     'fontunits', 'normalized', 'fontsize',0.65,...
%                     'string','0');        
                               
E.pb_utilis = uicontrol(E.bg_misc(1),...
                  'style','popupmenu',...                 
                  'units','norm',...
                  'position',[0.49 0.3 0.29 0.6],...'position',[0.49 0.45 0.29 0.5],...
                  'string',{'Utils...','DynamicBC','Clustering','Spectrum','Visualization','Quit'},...
                  'TooltipString','...',...
                  'fontunits', 'normalized', 'fontsize',0.35);       

E.pb_runall = uicontrol(E.bg_misc(1),...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.8 0.05 0.2 0.45],...
                  'string',{'<Html><FONT color="blue" face="Comic Sans MS">RUN</font>'},...
                  'TooltipString','Check and Run it!',...
                  'fontunits', 'normalized', 'fontsize',0.65);  
E.pb_reset = uicontrol(E.bg_misc(1),...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.8 0.52 0.2 0.45],...
                  'string',{'<Html><FONT color="blue" face="Comic Sans MS">Reset</font>'},...
                  'fontunits', 'normalized', 'fontsize',0.6);     
% if ~(exist('matlabpool'))
%     set(E.tx_par,'enable','off');
%     set(E.ed_par,'enable','off');
% end

if ec
    set(E.pb_utilis,'string',{'Utils...','DynamicBC','Clustering','Spectrum','Visualization','Quit'});
    set(E.rd_rvw(3),'string','GCD');
    set([E.tx_rd11_tvmodel(:),E.ed_rd11_tvmodel(:)],'visible','on');
    set(E.rd_tvmodel(1),'val',1);
    set(E.rd_tvmodel(2),'vis','off','val',0);
    set([E.tx_rd11_tvmodel(:),E.ed_rd11_tvmodel(:)],'visible','on')
    set(E.bg_slw_fls(1),'Title','Time Alignment')
    set(E.rd_slw(:),'visible','on');
    set(E.rd_slw(1),'value',1);
    set(E.rd_fls_snr(:),'visible','off');
    set(E.tx_fls_snr(:),'visible','off');
    set(E.rd_fls_snr(:),'value',0);
    set(E.bg_slw_conn,'visible','on');
elseif fc
    set(E.pb_utilis,'string',{'Utils...','DynamicBC','Clustering','Spectrum','Visualization','Quit'}); 
    set(E.rd_rvw(3),'string','FCD');
    set([E.tx_rd11_tvmodel(:),E.ed_rd11_tvmodel(:)],'visible','off');
    set([E.tx_rd11_tvmodel(3),E.ed_rd11_tvmodel(3)],'enable','off');
end 

set(E.rd_seed_ROI,'callback',{@wgr_seed_ROI_mode_call,E});
set(E.rd_seed_ROI(1),'callback',{@wgr_seed_ROI_mask_call,E});
set(E.pb_utilis,'callback',{@wgr_utilis_call,E});     
set(E.rd_tvmodel(1:2),{'callback'},{{@wgr_tv_mode_call,E}});
set(E.rd_fls_snr(:),'callback',{@wgr_fls_snr_call,E});
set(E.rd_rvw(:),'callback',{@ROIwise_call,E});
set(E.rd_mr(:),'callback',{@mask_datadir_mat_call,E});
ROIwise_call([],[],E);

set(E.pb_mask_dir,'callback',{@wgr_select_dir,E,'any',''});
set(E.pb_datadir,'callback',{@wgr_select_dir,E,'dir','in'});

set(E.pb_datadir_out,'callback',{@wgr_select_dir,E,'dir','out'});
set(E.pb_runall,'callback',{@wgr_run_all,E});
set(E.pb_reset,'callback',{@wgr_reset,E});
end

%%==============================================================
function [] = wgr_utilis_call(varargin)
E = varargin{3};
S = E.S;
flag_utilis = get(E.pb_utilis,'val');
str_utilis = get(E.pb_utilis,'string');
% 'Dynamic EC','Dynamic FC','Set defaults','Batch','Utilities','Quit'

switch str_utilis{flag_utilis};
    case 'DynamicBC'
        try 
            delete(S.fig)
        end
        DynamicBC;    
    case 'Spectrum'
        DynamicBC_SpectrumGUI;
    case  'Clustering'
        DynamicBC_Cluster;
    case 'Visualization'
            DynamicBC_CONGRAMGUI;
    case 'Quit'
        delete(E.fig);
end
end

function []=wgr_seed_ROI_mode_call(varargin)
E = varargin{3};  % Get structure.
flag_seed_mask = cell2mat(get(E.rd_seed_ROI,'val'));
if flag_seed_mask(1) & ~flag_seed_mask(2)
   set(E.rd_seed_ROI(1),'val',1);
   set(E.rd_seed_ROI(2),'val',0);
   set([E.ed_MNI(:),E.tx_MNI(:)],'enable','off');
elseif ~flag_seed_mask(1) & flag_seed_mask(2)
   set(E.rd_seed_ROI(2),'val',1);
   set(E.rd_seed_ROI(1),'val',0);
   set([E.ed_MNI(:),E.tx_MNI(:)],'enable','on');
elseif ~flag_seed_mask(1) & ~flag_seed_mask(2)
   set(E.rd_seed_ROI(1),'val',1);
   set(E.rd_seed_ROI(2),'val',0);
   set([E.ed_MNI(:),E.tx_MNI(:)],'enable','off');
end
end

function []=wgr_seed_ROI_mask_call(varargin)
E = varargin{3};  % Get structure.
flag_ROI_mask = get(E.rd_seed_ROI(1),'val');
if flag_ROI_mask
    mask_file = spm_select(1,'image','Select ROI mask (NIFTI file)');
%     while isempty(mask_file)
%         fprintf('Sorry, you do not select one NIFTI mask image!\n');
%         mask_file = spm_select(1,'image','Select ROI mask (NIFTI file)');
%     end
    set(E.rd_seed_ROI(1),'TooltipString',mask_file);
    set(E.ed_MNI(:),'enable','off');
end
end

function []=wgr_tv_mode_call(varargin)
E = varargin{3};  % Get structure.
R = [get(E.rd_tvmodel(1),'val'), get(E.rd_tvmodel(2),'val')];  % Get state of radios.
E_bg_tvmodel_pos = E.bg_tvmodel_pos;
R1 = cell2mat(get(E.rd_rvw,'val'));

if R(1)==1 && R(2)==0
    set(E.rd_tvmodel(1),'position',[0.1 0.55 0.8 0.45]);
    set(E.rd_tvmodel(2),'position',[0.6 0.01 0.35 0.45]);
    set([E.tx_rd11_tvmodel(1:2),E.ed_rd11_tvmodel(1:2)],'visible','on');
%     set(E.tx_slw(:),'visible','on');
    set(E.bg_slw_fls(1),'Title','Time Alignment')
%     set([E.tx_fls_para],'visible','off');
    set(E.rd_slw(:),'visible','on');
    set(E.rd_slw(1),'value',1);
    set(E.rd_fls_snr(:),'visible','off');
    set(E.tx_fls_snr(:),'visible','off');
    set(E.rd_fls_snr(:),'value',0);
    set(E.bg_slw_conn,'visible','on');

    if sum(R1(1:2)) % control p-value
        set([E.rd_slw_conn(:);E.ed_slw_pvalue(1)],'enable','off')
        set(E.ed_slw_pvalue(1),'str','no');
    else
        set([E.rd_slw_conn(:);E.ed_slw_pvalue(1)],'enable','on')
        set(E.ed_slw_pvalue(1),'str','0.001');
    end
    set(E.rd_fls_snr(:),'callback',{@wgr_fls_snr_call,E});
else %fls
    set(E.rd_tvmodel(2),'position',[0.1 0.1 0.8 0.45]);
    set(E.rd_tvmodel(1),'position',[0.1 0.55 0.8 0.45]);
    set([E.tx_rd11_tvmodel(:),E.ed_rd11_tvmodel(:)],'visible','off');
%     set(E.tx_slw(:),'visible','off');
    set(E.bg_slw_fls(1),'Title','FLS Parameter')
    set(E.bg_slw_conn,'visible','off');
%     set([E.tx_fls_para],'visible','on');
    set(E.rd_slw(:),'visible','off');
    set(E.rd_slw(:),'value',0);
    set(E.rd_fls_snr(:),'visible','on'); 
    flag_auto_fix = cell2mat(get(E.rd_fls_snr(:),'value'));
    if ~sum(flag_auto_fix)
        set(E.rd_fls_snr(2),'value',1);
        set(E.tx_fls_snr(2),'visible','on'); 
    end
    set(E.rd_fls_snr(:),'callback',{@wgr_fls_snr_call,E});
    
end
end

function []=ROIwise_call(varargin)
E = varargin{3};
R1 = cell2mat(get(E.rd_rvw,'val'));
R2 = cell2mat(get(E.rd_mr,'val'));
R = cell2mat(get(E.rd_tvmodel,'val'));  % Get state of radios.

if sum(R1([1 3]))
    if ~sum(R2(1:2))
        set(E.rd_mr(1),'val',1);
    end
    if R1(1)
        set(E.bg_seed_voxel,'visible','on');
        set(E.bg_seed_ROI,'visible','on');
    else%if R1(3)
        set(E.bg_seed_voxel,'visible','off');
        set(E.bg_seed_ROI,'visible','off');
    end
    set(E.tx_mask,'string','Mask');
    set(E.bg_mr(1),'Title','Mask');
    set(E.rd_mr(1:2),'visible','on');
    set(E.rd_mr(3:5),'visible','off');
else
    if sum(R2(1:2))
        set(E.rd_mr(4),'val',1);
    end   
    set(E.bg_seed_voxel,'visible','off');
    set(E.bg_seed_ROI,'visible','off');
    set(E.tx_mask,'string','ROI');
    set(E.bg_mr(1),'Title','ROI');
    set(E.rd_mr(1:2),'visible','off');
    set(E.rd_mr(3:5),'visible','on');    
end    

if sum(R1(1:2))
    set([E.rd_slw_conn(:);E.ed_slw_pvalue(1)],'enable','off')
    set(E.ed_slw_pvalue(1),'str','no');
else
    set([E.rd_slw_conn(:);E.ed_slw_pvalue(1)],'enable','on')
    set(E.ed_slw_pvalue(1),'str','0.001');
end
mask_datadir_mat_call([],[],E);
end

function []=mask_datadir_mat_call(varargin)
E = varargin{3};
R2 = cell2mat(get(E.rd_mr,'val'));
R3 = R2(5);
if R3
    set(E.ed_mat,'visible','on');
else
    set(E.ed_mat,'visible','off');
end
if R2(1)
    set(E.tx_mask,'enable','off');
    set(E.pb_mask_dir,'enable','off');
    set(E.ed_mrs,'enable','off');
    set(E.ed_mrs,'str','reslice brain mask in SPM');
else
    set(E.tx_mask,'enable','on');
    set(E.pb_mask_dir,'enable','on');
    set(E.ed_mrs,'enable','on');
    set(E.ed_mrs,'str','not selected');
end

if sum(R2(4:5))
    set(E.tx_mrs,'enable','off');
    set(E.ed_bg_data_dir,'enable','off');
    set(E.pb_datadir,'enable','off');
    set(E.ed_bg_data_dir,'str',''); %select files in above line
else
    set(E.tx_mrs,'enable','on');
    set(E.ed_bg_data_dir,'enable','on');
    set(E.pb_datadir,'enable','on');
%     set(E.ed_bg_data_dir,'str','not selected');
end
end

function [] = wgr_fls_snr_call(varargin)
E = varargin{3};
flag_auto_fix = cell2mat(get(E.rd_fls_snr(:),'value'));
if ~sum(flag_auto_fix) | flag_auto_fix(2)
    set(E.rd_fls_snr(2),'value',1);
    set(E.rd_fls_snr(1),'value',0);
    set(E.tx_fls_snr(2),'visible','on'); 
    set(E.tx_fls_snr(1),'visible','off');      
elseif flag_auto_fix(1)
    set(E.tx_fls_snr(1),'visible','on'); 
    set(E.rd_fls_snr(1),'value',1);
    set(E.tx_fls_snr(2),'visible','off');      
    set(E.rd_fls_snr(2),'value',0);
end
end


function [] = wgr_select_dir(varargin)
E = varargin{3};
str = varargin{4};
io = varargin{5};
if strcmp(io ,'in')
    data_dir = spm_select(inf,str);
    set(E.ed_bg_data_dir,'string',data_dir);
elseif strcmp(io ,'out')
    data_dir = spm_select(inf,str);
    set(E.ed_bg_dir_out,'string',data_dir);
else
    files = spm_select(inf,str);
    set(E.ed_mrs_files,'string',files);    
    num = size(files,1);
    data_dir=[]; data_dir2=[];
    for i=1:num
        fname = strcat(files(i,:));
        [pathstr, name, ext] = fileparts(fname);
        if i==1
            data_dir = [data_dir,fname];
            data_dir2 = [data_dir2,name];
        else
            data_dir = [data_dir,'; ',fname];
            data_dir2 = [data_dir2,'; ',name];
        end
    end
    set(E.ed_mrs,'string',data_dir);
    set(E.tx_mask,'TooltipString',data_dir2);
end
end

function [] = wgr_reset(varargin)
E = varargin{3};
set(E.ed_bg_data_dir,'string','not selected');
set(E.ed_bg_dir_out,'string','not selected');
set(E.ed_mrs,'string','not selected');
set(E.ed_prefix,'string','');
set(E.ed_par,'string','');
end

function [] = wgr_run_all(varargin)
E = varargin{3};
F.E = E;
if E.fc_ec(1)
    fc_ec = 'Dynamic Functional Connectivity';
elseif E.fc_ec(2)
    fc_ec = 'Dynamic Effective Connectivity';
end
% set(E.S.fig,'Visible','off');
try
    delete(E.S.fig);
end
work_dir = get(E.ed_bg_data_dir,'string');
numlim = 40;
num0 = length(work_dir);
if num0>numlim;
    work_dir2 = [];
    num_bin = ceil(num0./numlim);
    for i=1:num_bin
        if i~=num_bin
            ind0 = [(i-1)*numlim+1] : i*numlim;
        else
            ind0 = [(i-1)*numlim+1] : num0;
        end        
        work_dir2 = [work_dir2  work_dir(ind0) ' '];
    end
else
    work_dir2 = work_dir;
end
    
tvmodel_id = cell2mat(get(E.rd_tvmodel,'val'));
tvmodel_id = find(tvmodel_id>0);
tvmodel = get(E.rd_tvmodel(tvmodel_id),'string');
if tvmodel_id==2 % fls
    fls_snr_id = find(cell2mat(get(E.rd_fls_snr,'val'))>0);
    fls_snr_str = get(E.rd_fls_snr(fls_snr_id),'string');
    fls_snr = get(E.tx_fls_snr(fls_snr_id),'string');
    slw_fls_str = ['SNR:',fls_snr_str, '(', fls_snr,')'];
elseif tvmodel_id==1 % sliding windows
    slw_id = find(cell2mat(get(E.rd_slw,'val'))>0);
    slw_alignment = get(E.rd_slw(slw_id),'string');
    slw_winsize_str = get(E.tx_rd11_tvmodel(1),'string');
    slw_winsize = get(E.ed_rd11_tvmodel(1),'string');
    slw_overlap_str = get(E.tx_rd11_tvmodel(2),'string');
    slw_overlapsize = get(E.ed_rd11_tvmodel(2),'string');
    slw_order_str = get(E.tx_rd11_tvmodel(3),'string');
    slw_order = get(E.ed_rd11_tvmodel(3),'string');
    slw_fls_str = [slw_alignment,'; ',slw_winsize_str,slw_winsize,...
        '; ',slw_overlap_str,slw_overlapsize];
    if E.fc_ec(2)
        slw_fls_str = [slw_fls_str,'; ',slw_order_str,slw_order];
    end
end
rd_rvw_id = cell2mat(get(E.rd_rvw,'val'));
set_roi = get(E.rd_rvw(find(rd_rvw_id>0)),'string');
mask_roi = get(E.ed_mrs,'string');
out_dir = get(E.ed_bg_dir_out,'string');
num0 = length(out_dir);
if num0>numlim;
    out_dir2 = [];
    num_bin = ceil(num0./numlim);
    for i=1:num_bin
        if i~=num_bin
            ind0 = [(i-1)*numlim+1] : i*numlim;
        else
            ind0 = [(i-1)*numlim+1] : num0;
        end        
        out_dir2 = [out_dir2  out_dir(ind0) ' '];
    end
else
    out_dir2 = out_dir;
end
    
prefix_name = get(E.ed_prefix(1),'string');
% log_name = get(E.ed_log_name(1),'string');
mat_flag = get(E.rd_mr(5),'val');
if mat_flag
    mat_name = ['<FONT color="blue">---variable_name:',get(E.ed_mat(1),'string')];
else
    mat_name='';
end
% spar_num = get(E.ed_par(1),'string');
str_run = 'Finish editing the configuration parameters?';
str_par = 'Note: Please configure the Matlab Parallel Computing by yourself. (type "matlabpool" or "parpool " in the command window)';

mytext = ['<html><body><table border="1">' ...
          '<tr><th><FONT color="red" size="+1.5" face="Comic Sans MS">Check Parameters Settings</font></th></tr>' ...
          ['<tr><td><center>',fc_ec,'</td></tr>'] ...
          '<tr><th>Working Directory</th></tr>' ...
          ['<tr><td><center>',work_dir2,'</td></tr>'] ...
          ['<tr><th>TV model: <FONT color="blue">',tvmodel,'</th></tr>'] ...
          ['<tr><td><center>',slw_fls_str,'</td></tr>'] ...
          ['<tr><th>Set ROI: <FONT color="blue">',set_roi,'</th></tr>'] ...
          ['<tr><th>Mask/ROI',mat_name,'</th></tr>'] ...
          ['<tr><td><center>',mask_roi,'</td></tr>'] ...
          '<tr><th>Output Directory</th></tr>' ...
          ['<tr><td><center>',out_dir2,'</td></tr>'] ...
          ['<tr><td><center>Prefix:<FONT color="blue">',prefix_name,' <FONT color="black">'] ...Logfile:<FONT color="blue">',log_name,' <FONT color="black">; 
          ['<tr><FONT color="red" size="+0.5" face="Comic Sans MS">',str_run,'</font></tr>'] ...
          ['<tr><FONT color="blue" size="+0.5" face="Comic Sans MS">',str_par,'</font></tr>'] ...
          '</table></body></html>'
          ];
if strcmpi(strcat(work_dir),strcat(out_dir));
    error('DynamicBC error: The data directory is same with output directory, Please change the output directory!')
end      
F.hfig = figure('name',['Configurations Checking(',getenv('USERNAME'),')'],...
              'Visible','on',...
              'numbertitle','off',...
              'menubar','none',...              'units','normalized',...
              'color','w',...              'position',[0.3 0.3 0.265 0.65]);   
              'position',[150  150  320  600]);
je = javax.swing.JEditorPane('text/html', mytext);
jp = javax.swing.JScrollPane(je);
[hcomponent, hcontainer] = javacomponent(jp, [], F.hfig);
set(hcontainer, 'units', 'normalized', 'position', [0,0,1,1]);
movegui(F.hfig,'center');

F.pb_run_check(1) = uicontrol(F.hfig,...
                    'style','pushbutton',...
                    'units','normalized',...
                    'position',[0.6 0.02 0.35 0.08],...
                    'string','Yes&Run',...       
                    'fontweight','bold',...
                    'fontname','Comic Sans MS',...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'foregroundcolor',[0 0 .8],...
                    'backgroundc',get(F.hfig,'color'),...
                    'value',0,...
                    'TooltipString','yes and run it');
F.pb_run_check(2) = uicontrol(F.hfig,...
                    'style','pushbutton',...
                    'units','normalized',...
                    'position',[0.05 0.02 0.4 0.08],...
                    'string','No&return',...       
                    'fontweight','bold',...
                    'fontname','Comic Sans MS',...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'foregroundcolor',[0 0 .8],...
                    'backgroundc',get(F.hfig,'color'),...
                    'value',0,...
                    'TooltipString','no and please change it'); 
F.pb_run_check(3) = uicontrol(F.hfig,...
                    'style','pushbutton',...
                    'units','normalized',...
                    'position',get(F.pb_run_check(2),'position'),...
                    'string','Unlock Run',...       
                    'fontweight','bold',...
                    'fontname','Comic Sans MS',...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'foregroundcolor',[0 0 .8],...
                    'backgroundc',get(F.hfig,'color'),...
                    'value',0,...
                    'Visible','off',...
                    'TooltipString','stop!');                   
                
set(F.pb_run_check(:),'callback',{@wgr_run_check,F});
end

function [] = wgr_run_check(varargin)
F = varargin{3};
flag = find(cell2mat(get(F.pb_run_check(:),'val'))>0);
if flag==2
    delete(F.hfig);
elseif flag==1
    disp('Running now!')    
    set(F.pb_run_check(1),'Visible','on');
    set(F.pb_run_check(3),'Visible','on');
    set(F.pb_run_check(1),'backgroundc',[0.75 0 0.75]);
    set(F.pb_run_check(1),'Enable', 'off');
    movegui(F.hfig,'east');
    DynamicBC_run(F)
elseif flag==3
    fprintf('Unlock successful!\n')
    set(F.pb_run_check(1),'Visible','on');
    set(F.pb_run_check(1),'Enable', 'on');
    set(F.pb_run_check(2),'Visible','on');
    set(F.pb_run_check(3),'Visible','off');
    set(F.pb_run_check(1),'backgroundc',get(F.hfig,'color')); 
    movegui(F.hfig,'center');
end
end