function [] = DynamicBC(varargin)
% Dynamic Brain Connectome analysis toolbox.
% First coded at Aug/8/2013.
% revised code at Feb/1/2014.
% revised code at Mar/21/2014.
% revised code at Mar/25/2014.
% revised code at July/2/2014.

% close all
DynamicBC_path = fileparts(which('DynamicBC.m'));
addpath(genpath(DynamicBC_path));
logo_gif = fullfile(DynamicBC_path,'DynamicBC_logo.gif');

S.fig = figure('Visible','off',...
              'numbertitle','off',...
              'menubar','none',...              'units','normalized',... 
              'color','w',...
              'position',[563    98   414   376],...[0.4   0.4    0.309    0.5],...
              'name',['DynamicBC Version 1.1(',getenv('USERNAME'),')'],...
              'resize','off');
Colo_bg = ones(1,3)*0.85;
S.Colo_bg = Colo_bg;
%  fprintf(' If you want to get more information on TVCT, \n Please email us: gronwu@gmail.com (Guo-Rong Wu), xuqiangnj12@gmail.com(Qiang Xu), weiliao.wl@gmail.com (Wei Liao)\n')
%%===================Title===========================================

S.bg(1) = uibuttongroup('units','normalized',...
    'backgroundc',Colo_bg,...
                     'pos',[0.01 0.64 0.98 0.35]);                 
pos_s = [0.01 0.3 0.98 0.6
         0.01 0.3 0.98 0.4
         0.01 0.08 0.98 0.15];
col_s = [1 0 0;
         0 0 1;
         0.9 0.1 0.1];
str_s = {'Dynamic Brain Connectome Analysis Toolbox',...
    'DynamicBC',...
    'Center for Cognition and Brain Disorders, Hangzhou Normal University'};
siz_s = [0.22 0.8 0.55];
for i=1:3
    S.tx(i) = uicontrol(S.bg(1),'style','text',...
     'unit','normalized',...
     'position',pos_s(i,:),... 
     'string',str_s{i},...
     'backgroundc',Colo_bg,...
     'foregroundcolor',col_s(i,:),...
     'fontname','Arial',...
     'fontunits', 'normalized', 'fontsize',siz_s(i),... 
     'fontweight','bold');
end
%%======================FC / EC========================================
S.bg(2) = uibuttongroup('units','normalized',...
    'backgroundc',Colo_bg,...
                     'pos',[0.01 0.01 0.98 0.62]);             
S.pb(1) = uicontrol(S.bg(2),...
                    'style','pushbutton',...
                    'units','normalized',...
                    'position',[0.5 0.6 0.45 0.25],... 
                    'string',{'<Html><FONT color="blue" face="Comic Sans MS">Dynamic FC</font>'},... 
                    'fontunits', 'normalized', 'fontsize',0.45,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'TooltipString','Time varying Functional connectivity');
S.pb(2) = uicontrol(S.bg(2),...
                    'style','pushbutton',...
                    'units','normalized',...
                    'position',[0.5 0.2 0.45 0.25],... 
                    'string',{'<Html><FONT color="blue" face="Comic Sans MS">Dynamic EC</font>'},...
                    'fontunits', 'normalized', 'fontsize',0.45,... 
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'enable','on');             
                
je = javax.swing.JEditorPane('text/html', ['<html><img src=file:/',logo_gif,'/></html>']);
je.setBackground(java.awt.Color(0.85,0.85,0.85));  
[hj, hc] =  javacomponent(je,[],S.fig);
set(hc, 'units','normalized','pos', [0.05,0.05,0.45,0.45]);
%%==============================================================

movegui(S.fig,'center');
% Make the GUI visible.
set(S.fig,'Visible','on','resize','on');
set(S.pb(1:2),{'callback'},{{@pb_call,S}});


function [E] = pb_call(varargin)
% Callback for togglebuttons.
S = varargin{3};  % Get the structure.
%%==============================================================
E.S = S;
fc = get(S.pb(1),'val');
ec = get(S.pb(2),'val');
if ec
    disp('Dynamic Effective Connectivity---setting');
elseif fc
    disp('Dynamic Functional Connectivity---setting');
end
E.fc_ec = [fc ec];
movegui(S.fig,'west');

E.fig = figure('Name','Parameter Setup',...       'units','normalized',...
       'menubar','none',...
       'numbertitle','off',...       
       'position',get(S.fig,'pos')*1.5);

movegui(E.fig,'center');
   
%%=============================Configurations=================================
E_bg_title_pos = [0.01 0.9 0.985 0.096];
E.bg_title(1) = uibuttongroup('units','norm',...
                     'pos',E_bg_title_pos);  
E.tx_title(1) = uicontrol(E.bg_title(1),...
                'style','text',...
                'units','normalized',...
                'position',[0.05 0.1 0.9 0.8],...         
                'string','Configurations',...
                'backgroundc',get(E.bg_title(1),'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.75,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .8]);
if ec
    set(E.tx_title(1),'string','Configurations (EC)') ;
elseif fc
    set(E.tx_title(1),'string','Configurations (FC)') ;
end            
%%===========================TV Model===================================
E_bg_tvmodel_pos = [0.535 0.56 0.46 0.3];
E.bg_tvmodel_pos = E_bg_tvmodel_pos;
E.bg_tvmodel(1) = uibuttongroup('Parent',E.fig,...
                     'units','normalized',... 
                     'pos',E_bg_tvmodel_pos);   
                 
E.rd_tvmodel(1) = uicontrol('Parent',E.bg_tvmodel(1),...
                    'style','rad',...
                    'units','normalized',...
                    'position',[0.1 0.5 0.8 0.45],...
                    'string',' Sliding-window',...                    
                    'backgroundc',get(E.bg_title(1),'backgroundc'),...                    
                    'fontweight','bold',...                
                    'fontunits', 'normalized', 'fontsize',0.25,...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','Sliding-window Analysis');  
E.rd_tvmodel(2) = uicontrol('Parent',E.bg_tvmodel(1),...
                    'style','rad',...
                    'units','normalized',...
                    'position',[0.1 0.1 0.8 0.45],...
                    'string','   FLS',...                    
                    'backgroundc',get(E.bg_title(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.25,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','Flexible Least Square Analysis');     
E.tx_tvmodel(1) = uicontrol(E.bg_tvmodel(1),...
                'style','text',...
                'units','normalized',...
                'position',[0.25 0.92 0.5 0.2],...
                'string','TV mode',...                
                'fontunits', 'normalized', 'fontsize',0.7,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .1]);       

pos_rd11 = [0.01 0.37 0.4 0.22;
            0.015 0.03 0.3 0.25;
            0.48 0.03 0.35 0.25;
            0.55 0.43 0.35 0.18;
            0.3 0.1 0.15 0.2
            0.85 0.1 0.14 0.2
            ];
str_rd11 ={'Window Size:','Overlap:','(GC)Order:','50','0.6','1'};       
for i=1:3
    E.tx_rd11_tvmodel(i) = uicontrol(E.bg_tvmodel(1),...
                    'style','text',...
                    'units','normalized',...
                    'position',pos_rd11(i,:),...
                    'string',str_rd11{i},...                
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'visible','on',...
                    'foregroundcolor',[.8 .1 .1]);   
    E.ed_rd11_tvmodel(i) = uicontrol(E.bg_tvmodel(1),...
                        'style','edit',...
                        'unit','norm',...
                        'position',pos_rd11(i+3,:),...
                        'fontunits', 'normalized', 'fontsize',0.45,...
                        'string',str_rd11{i+3});   
end
                
%%=====================SLW-FLS parameter=========================================
%% 
E_bg_slw_fls_pos = [0.535 0.35 0.46 0.18];
E.bg_slw_fls_pos = E_bg_slw_fls_pos;
E.bg_slw_fls(1) = uibuttongroup('units','norm',...
                     'pos',E_bg_slw_fls_pos);   
                 
E.rd_slw(1) = uicontrol('Parent',E.bg_slw_fls(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.01 0.5 0.8 0.45],...
                    'string',' Ahead',...                    
                    'backgroundc',get(E.bg_slw_fls(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');  
E.rd_slw(2) = uicontrol('Parent',E.bg_slw_fls(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.4 0.5 0.5 0.45],...
                    'string','  Middle',...                    
                    'backgroundc',get(E.bg_slw_fls(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');     
E.bg_slw_conn(1) = uibuttongroup('Parent',E.bg_slw_fls(1),...
                     'units','norm',...
                     'pos',[0.01 0.01 0.98 0.48]);                  
E.rd_slw_conn(1) = uicontrol('Parent',E.bg_slw_conn(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.01 0.05 0.5 0.65],...
                    'string','FWE',...                    
                    'backgroundc',get(E.bg_slw_conn(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.6,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');  
E.rd_slw_conn(2) = uicontrol('Parent',E.bg_slw_conn(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.3 0.05 0.5 0.65],...
                    'string','Fixed',...                    
                    'backgroundc',get(E.bg_slw_conn(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.6,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');   
E.ed_slw_pvalue = uicontrol('Parent',E.bg_slw_conn(1),...
                    'style','edit',...
                    'units','norm',...
                    'position',[0.64 0.05 0.35 0.6],...
                    'string','0.001',...                    
                    'backgroundc',get(E.bg_slw_conn(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.7,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');                  
E.rd_fls_snr(1) = uicontrol('Parent',E.bg_slw_fls(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.1 0.5 0.8 0.45],...
                    'string','   Default',...                    
                    'backgroundc',get(E.bg_slw_fls(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.39,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');  
E.rd_fls_snr(2) = uicontrol('Parent',E.bg_slw_fls(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.1 0.1 0.8 0.45],...
                    'string','   Fixed',...                    
                    'backgroundc',get(E.bg_slw_fls(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');     
                
E.tx_fls_snr(1) = uicontrol(E.bg_slw_fls(1),...
                    'style','text',...
                    'unit','norm',...
                    'position',[0.5 0.53 0.3 0.32],...
                    'fontunits', 'normalized', 'fontsize',0.55,...
                    'visible','off',...
                    'string','100');                 

E.tx_fls_snr(2) = uicontrol(E.bg_slw_fls(1),...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.5 0.15 0.3 0.32],...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'visible','on',...
                    'string','100'); 
                
E.tx_slw(1) = uicontrol(E.bg_slw_fls(1),...
                'style','text',...
                'units','norm',...
                'position',[0.2 0.92 0.6 0.24],...
                'string','Time Alignment',...                
                'fontunits', 'normalized', 'fontsize',0.8,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .1]);       
E.tx_slw(2) = uicontrol(E.bg_slw_fls(1),...
                'style','text',...
                'units','norm',...
                'position',[0.08 0.34 0.85 0.23],...
                'string','Connectivity p-value',...                
                'fontunits', 'normalized', 'fontsize',0.8,...
                'visible','off',...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .1]);
E.tx_fls_para = uicontrol(E.bg_slw_fls(1),...
                'style','text',...
                'units','norm',...
                'position',[0.2 0.92 0.6 0.24],...
                'string','FLS Parameter',...                
                'fontunits', 'normalized', 'fontsize',0.8,...
                'fontweight','bold',...
                'visible','on',...
                'foregroundcolor',[.8 .1 .1]);      

%%===========================ROI-voxel wise===================================
E_bg_rvw_pos = [0.01 0.56 0.50 0.3];
E.bg_rvw = uibuttongroup('Parent',E.fig,...
                     'units','norm',...
                     'pos',E_bg_rvw_pos);   
rvw_pos =[0.08 0.7 0.5 0.2;
          0.08 0.4 0.5 0.2;
          0.08 0.05 0.5 0.2;];
rvw_str = {'Voxel wise','ROI wise','FCD'};
rvw_val = [1 0 0];
for i=1:3
    E.rd_rvw(i) = uicontrol('Parent',E.bg_rvw,...
                'style','rad',...
                'units','norm',...
                'position',rvw_pos(i,:),...
                'string',rvw_str{i},...                    
                'backgroundc',get(E.bg_rvw,'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.6,...
                'fontweight','bold',...
                'foregroundcolor',[0 0 .8],...
                'value',rvw_val(i));  
end

%% seed MNI-ROI
E.bg_seed_ROI = uibuttongroup('Parent',E.bg_rvw,...
                     'units','norm',...
                     'pos',[0.58 0.67 0.42 0.33]);   
seed_ROI_str = {'ROI-Mask','Seed(MNI)'};
seed_ROI_pos = [0.15 0.5 0.8 0.48;
                0.15 0.05 0.8 0.48];
for i=1:2
    E.rd_seed_ROI(i) = uicontrol(E.bg_seed_ROI,...
                    'style','rad',...
                    'units','norm',...
                    'position',seed_ROI_pos(i,:),...
                    'string',seed_ROI_str{i},...                
                    'fontunits', 'normalized', 'fontsize',0.6,...
                    'fontweight','bold',...
                    'val',1,...
                    'enable','on',...
                    'foregroundcolor',[.8 .1 .1]); 
end
           
%% seed MNI input
E.bg_seed_voxel = uibuttongroup('Parent',E.bg_rvw,...
                     'units','norm',...
                     'pos',[0.58 0.01 0.42 0.65]);   

xyz_height = [0.75 0.5 0.26 0.01];  
xyz_label = {'x','y','z','radius'};
xyz_val = {'0','-53','26','6'};
for xyz=1:4       
    E.ed_MNI(xyz) = uicontrol('Parent',E.bg_seed_voxel,...
                        'style','edit',...
                        'units','norm',...
                        'position',[0.4 xyz_height(xyz) 0.58 0.22],...
                        'string',[xyz_val{xyz}],...                    
                        'backgroundc',get(E.bg_slw_conn(1),'backgroundc'),...
                        'fontunits', 'normalized', 'fontsize',0.6,...
                        'fontweight','bold',...
                        'horizontalalign','center',...
                        'foregroundcolor',[0 0 .8],...
                        'value',1,...
                        'TooltipString',[xyz_label{xyz},'-coordinate']); 
    
    E.tx_MNI(xyz) = uicontrol('Parent',E.bg_seed_voxel,...
                        'style','text',...
                        'units','norm',...
                        'position',[0.01 xyz_height(xyz) 0.38 0.22],...
                        'string',[xyz_label{xyz},': = '],...                    
                        'backgroundc',get(E.bg_slw_conn(1),'backgroundc'),...
                        'fontunits', 'normalized', 'fontsize',0.6,...
                        'fontweight','bold',...
                        'horizontalalign','center',...
                        'foregroundcolor',[0 0 .8],...
                        'value',1);  
                    
    if xyz==4
        set(E.ed_MNI(4),'String','6','TooltipString','Sphere radius -mm','position',get(E.ed_MNI(4),'position')+[0.15 0 -0.15 -0.02]);
        set(E.tx_MNI(4),'position',get(E.tx_MNI(4),'position')+[0 -0.01 0.1 0]);
    end                    
end  

E.tx_rvw(1) = uicontrol(E.bg_rvw,...
                'style','text',...
                'units','norm',...
                'position',[0.1 0.92 0.4 0.2],...
                'string','Set ROI',...                
                'fontunits', 'normalized', 'fontsize',0.7,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .1]);             
            
%%=========================Mask_ROI=====================================
E_bg_mr_pos = [0.01 0.35 0.50 0.18];
E.E_bg_mr_pos = E_bg_mr_pos;

E.ed_mrs_files = uicontrol('style','text',...
                    'visible','off',...
                    'string',' ');
                
E.bg_mr(1) = uibuttongroup('units','norm',...
                     'pos',E_bg_mr_pos);   
% mapping case.                 
E.rd_mr(1) = uicontrol('Parent',E.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.1 0.5 0.8 0.45],...
                    'string',' Default mask',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.39,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');  
E.rd_mr(2) = uicontrol('Parent',E.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.1 0.1 0.8 0.45],...
                    'string','User-Defined Mask',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',1,...
                    'TooltipString','...');     
% ROI wise case
E.rd_mr(3) = uicontrol('Parent',E.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.01 0.5 0.8 0.45],...
                    'string','Nifti Label',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');  
E.rd_mr(4) = uicontrol('Parent',E.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.6 0.5 0.3 0.45],...
                    'string','TXT',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');   
E.rd_mr(5) = uicontrol('Parent',E.bg_mr(1),...
                    'style','rad',...
                    'units','norm',...
                    'position',[0.01 0.1 0.75 0.45],...
                    'string','Mat,variable name:',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','center',...
                    'foregroundcolor',[0 0 .8],...
                    'value',0,...
                    'TooltipString','...');                   
E.ed_mat = uicontrol('Parent',E.bg_mr(1),...
                    'style','edit',...
                    'units','norm',...
                    'position',[0.75 0.1 0.2 0.4],...
                    'string','data',...                    
                    'backgroundc',get(E.bg_mr(1),'backgroundc'),...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'fontweight','bold',...
                    'horizontalalign','right',...
                    'foregroundcolor',[0 0 .8],...                   
                    'visible','off',...
                    'TooltipString','...');                  
  
E.tx_mr(1) = uicontrol(E.bg_mr(1),...
                'style','text',...
                'units','norm',...
                'position',[0.2 0.92 0.6 0.26],...
                'string','Mask/ROI',...               
                'fontunits', 'normalized', 'fontsize',0.8,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .1]);   
            
set(E.rd_mr(1:2),'visible','on');
set(E.rd_mr(3:5),'visible','off');
set(E.bg_slw_conn,'visible','off');
set(E.rd_slw(:),'visible','off');
  
%%=========================Mask_ROI_selection=====================================

E_bg_mrs_pos = [0.01 0.195 0.986 0.15];
E.bg_mrs(1) = uibuttongroup('parent',E.fig,...
                     'units','norm',...
                     'pos',E_bg_mrs_pos);    
E.tx_mask = uicontrol(E.bg_mrs(1),...
                'style','text',...
                'units','norm',...
                'position',[0.001 0.4 0.3 0.4],...
                'string','Mask/ROI:',...
                'backgroundc',get(E.bg_mrs(1),'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.5,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .8]);
E.ed_mrs = uicontrol(E.bg_mrs(1),...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.28 0.5 0.64 0.4],...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'string','not selected');       
E.pb_mask_dir = uicontrol(E.bg_mrs(1),...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.9 0.5 0.09 0.4],...
                  'string','...',...
                  'TooltipString','Click me!',...
                  'fontunits', 'normalized', 'fontsize',0.8);     
              
E.tx_mrs = uicontrol(E.bg_mrs(1),...
                'style','text',...
                'units','norm',...
                'position',[0.001 0.01 0.3 0.4],...
                'string','Data Directory:',...
                'backgroundc',get(E.bg_mrs(1),'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.5,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .8]);
E.ed_bg_data_dir = uicontrol(E.bg_mrs(1),...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.28 0.05 0.64 0.4],...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'string','not selected');       
E.pb_datadir = uicontrol(E.bg_mrs(1),...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.9 0.05 0.09 0.4],...
                  'string','...',...
                  'TooltipString','Click me!',...
                  'fontunits', 'normalized','fontsize',0.8);       
              
%%========================Out_put Misc======================================
E_bg_misc_pos = [0.01 0.01 0.985 0.18]; 
E.bg_misc(1) = uibuttongroup('parent',E.fig,'units','norm',...
                     'pos',E_bg_misc_pos);  
E.tx_prefix(1) = uicontrol(E.bg_misc(1),...
                'style','text',...
                'units','norm',...
                'position',[0.02 0.6 0.24 0.3],...       
                'string','Prefix(Output):',...            
                'fontunits', 'normalized', 'fontsize',0.5,...
                'fontweight','bold',...
                'visible','on',...
                'foregroundcolor',[.8 .1 .8]);   
E.ed_prefix(1) = uicontrol(E.bg_misc(1),...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.28 0.66 0.19 0.28],...
                    'fontunits', 'normalized', 'fontsize',0.5,...
                    'string','TV');   
              
E.tx_output_dir(1) = uicontrol(E.bg_misc(1),...
                'style','text',...                
                'unit','normalized',...
                'string','Out Directory:',...
                'position',[0.01 0.03 0.25 0.3],...'position',[0.01 0.01 0.25 0.2],...
                'backgroundc',get(E.bg_misc(1),'backgroundc'),...
                'fontunits', 'normalized', 'fontsize',0.6,...
                'fontweight','bold',...
                'foregroundcolor',[.8 .1 .8]);
E.ed_bg_dir_out = uicontrol(E.bg_misc(1),...
                    'style','edit',...
                    'unit','normalized',...
                    'position',[0.24 0.03 0.45 0.3],...'position',[0.26 0.01 0.65 0.2],...
                    'fontunits', 'normalized', 'fontsize',0.65,...
                    'string','not selected');       
E.pb_datadir_out = uicontrol(E.bg_misc(1),...
                  'style','pushbutton',...
                  'units','normalized',...
                  'position',[0.69 0.03 0.09 0.32],...'position',[0.91 0.005 0.09 0.25],...
                  'string','...',...
                  'fontunits', 'normalized','fontsize',0.8,...
                  'TooltipString','Click me!');        
E.tx_par(1) = uicontrol(E.bg_misc(1),...
                  'style','text',...
                  'units','norm',...
                  'position',[0.03 0.32 0.29 0.3],...
                  'string','Parallel Workers #:',...
                  'horizontalalign','left',...
                  'fontunits', 'normalized', 'fontsize',0.6); 
E.ed_par(1) = uicontrol(E.bg_misc(1),...
                    'style','edit',...
                    'unit','norm',...
                    'position',[0.32 0.35 0.15 0.286],...
                    'fontunits', 'normalized', 'fontsize',0.65,...
                    'string','0');        
                               
E.pb_utilis = uicontrol(E.bg_misc(1),...
                  'style','popupmenu',...                 
                  'units','norm',...
                  'position',[0.49 0.45 0.29 0.5],...
                  'string',{'Utils...','Dynamic FC','Dynamic EC','Spectrum','Clustering','Quit'},...
                  'TooltipString','...',...
                  'fontunits', 'normalized', 'fontsize',0.35);       

E.pb_runall = uicontrol(E.bg_misc(1),...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.8 0.05 0.2 0.45],...
                  'string',{'<Html><FONT color="blue" face="Comic Sans MS">RUN</font>'},...
                  'TooltipString','Check and Run it!',...
                  'fontunits', 'normalized', 'fontsize',0.65);  
E.pb_reset = uicontrol(E.bg_misc(1),...
                  'style','pushbutton',...
                  'units','norm',...
                  'position',[0.8 0.52 0.2 0.45],...
                  'string',{'<Html><FONT color="blue" face="Comic Sans MS">Reset</font>'},...
                  'fontunits', 'normalized', 'fontsize',0.6);     
if ~(exist('matlabpool'))
    set(E.tx_par,'enable','off');
    set(E.ed_par,'enable','off');
end

if ec
    set(E.pb_utilis,'string',{'Utils...','Dynamic EC','Dynamic FC','Spectrum','Clustering','Quit'});
    set(E.rd_rvw(3),'string','GCD');
    set([E.tx_rd11_tvmodel(:),E.ed_rd11_tvmodel(:)],'visible','on');
    set(E.rd_tvmodel(1),'val',1);
    set(E.rd_tvmodel(2),'vis','off','val',0);
    set([E.tx_rd11_tvmodel(:),E.ed_rd11_tvmodel(:)],'visible','on');
    set(E.tx_slw(:),'visible','on');
    set([E.tx_fls_para],'visible','off');
    set(E.rd_slw(:),'visible','on');
    set(E.rd_slw(1),'value',1);
    set(E.rd_fls_snr(:),'visible','off');
    set(E.tx_fls_snr(:),'visible','off');
    set(E.rd_fls_snr(:),'value',0);
    set(E.bg_slw_conn,'visible','on');
elseif fc
    set(E.pb_utilis,'string',{'Utils...','Dynamic FC','Dynamic EC','Spectrum','Clustering','Quit'}); 
    set(E.rd_rvw(3),'string','FCD');
    set([E.tx_rd11_tvmodel(:),E.ed_rd11_tvmodel(:)],'visible','off');
    set([E.tx_rd11_tvmodel(3),E.ed_rd11_tvmodel(3)],'enable','off');
end 

set(E.rd_seed_ROI,'callback',{@wgr_seed_ROI_mode_call,E});
set(E.rd_seed_ROI(1),'callback',{@wgr_seed_ROI_mask_call,E});
set(E.pb_utilis,'callback',{@wgr_utilis_call,E});     
set(E.rd_tvmodel(1:2),{'callback'},{{@wgr_tv_mode_call,E}});
set(E.rd_fls_snr(:),'callback',{@wgr_fls_snr_call,E});
set(E.rd_rvw(:),'callback',{@ROIwise_call,E});
set(E.rd_mr(:),'callback',{@mask_datadir_mat_call,E});
ROIwise_call([],[],E);

set(E.pb_mask_dir,'callback',{@wgr_select_dir,E,'any',''});
set(E.pb_datadir,'callback',{@wgr_select_dir,E,'dir','in'});

set(E.pb_datadir_out,'callback',{@wgr_select_dir,E,'dir','out'});
set(E.pb_runall,'callback',{@wgr_run_all,E});
set(E.pb_reset,'callback',{@wgr_reset,E});

%%==============================================================
function [] = wgr_utilis_call(varargin)
E = varargin{3};
S = E.S;
flag_utilis = get(E.pb_utilis,'val');
str_utilis = get(E.pb_utilis,'string');
% 'Dynamic EC','Dynamic FC','Set defaults','Batch','Utilities','Quit'
flag_fc_ec = cell2mat(get(S.pb,'value'));
if ~sum(flag_fc_ec)
    flag_fc_ec = E.fc_ec;
end
switch str_utilis{flag_utilis};
    case 'Dynamic EC'
        if flag_fc_ec(1)
            set(S.pb(1),'val',0);
            set(S.pb(2),'val',1);
            delete(E.fig);
            E = pb_call([],[],S);
            E.fc_ec = [0 1];
            set(E.rd_rvw(3),'string','GCD');
            set(E.tx_title(1),'string','Configurations (EC)') ;
        end
    case 'Dynamic FC'
        if flag_fc_ec(2)
            set(S.pb(1),'val',1);
            set(S.pb(2),'val',0);
            delete(E.fig);
            E = pb_call([],[],S);
            E.fc_ec = [0 1];
            set(E.rd_rvw(3),'string','FCD');
            set(E.tx_title(1),'string','Configurations (FC)') ;
        end
    case 'Spectrum'
        DynamicBC_Spectrum;
    case  'Clustering'
        DynamicBC_Cluster_beta;
    case 'Quit'
        delete(E.fig);
end

function []=wgr_seed_ROI_mode_call(varargin)
E = varargin{3};  % Get structure.
flag_seed_mask = cell2mat(get(E.rd_seed_ROI,'val'));
if flag_seed_mask(1) & ~flag_seed_mask(2)
   set(E.rd_seed_ROI(1),'val',1);
   set(E.rd_seed_ROI(2),'val',0);
   set([E.ed_MNI(:),E.tx_MNI(:)],'enable','off');
elseif ~flag_seed_mask(1) & flag_seed_mask(2)
   set(E.rd_seed_ROI(2),'val',1);
   set(E.rd_seed_ROI(1),'val',0);
   set([E.ed_MNI(:),E.tx_MNI(:)],'enable','on');
elseif ~flag_seed_mask(1) & ~flag_seed_mask(2)
   set(E.rd_seed_ROI(1),'val',1);
   set(E.rd_seed_ROI(2),'val',0);
   set([E.ed_MNI(:),E.tx_MNI(:)],'enable','off');
end

function []=wgr_seed_ROI_mask_call(varargin)
E = varargin{3};  % Get structure.
flag_ROI_mask = get(E.rd_seed_ROI(1),'val');
if flag_ROI_mask
    mask_file = spm_select(1,'image','Select ROI mask (NIFTI file)');
%     while isempty(mask_file)
%         fprintf('Sorry, you do not select one NIFTI mask image!\n');
%         mask_file = spm_select(1,'image','Select ROI mask (NIFTI file)');
%     end
    set(E.rd_seed_ROI(1),'TooltipString',mask_file);
end

function []=wgr_tv_mode_call(varargin)
E = varargin{3};  % Get structure.
R = [get(E.rd_tvmodel(1),'val'), get(E.rd_tvmodel(2),'val')];  % Get state of radios.
E_bg_tvmodel_pos = E.bg_tvmodel_pos;
R1 = cell2mat(get(E.rd_rvw,'val'));

if R(1)==1 && R(2)==0
    set(E.rd_tvmodel(1),'position',[0.1 0.55 0.8 0.45]);
    set(E.rd_tvmodel(2),'position',[0.6 0.01 0.35 0.45]);
    set([E.tx_rd11_tvmodel(1:2),E.ed_rd11_tvmodel(1:2)],'visible','on');
    set(E.tx_slw(:),'visible','on');
    set([E.tx_fls_para],'visible','off');
    set(E.rd_slw(:),'visible','on');
    set(E.rd_slw(1),'value',1);
    set(E.rd_fls_snr(:),'visible','off');
    set(E.tx_fls_snr(:),'visible','off');
    set(E.rd_fls_snr(:),'value',0);
    set(E.bg_slw_conn,'visible','on');

    if sum(R1(1:2)) % control p-value
        set([E.rd_slw_conn(:);E.ed_slw_pvalue(1)],'enable','off')
        set(E.ed_slw_pvalue(1),'str','no');
    else
        set([E.rd_slw_conn(:);E.ed_slw_pvalue(1)],'enable','on')
        set(E.ed_slw_pvalue(1),'str','0.001');
    end
    set(E.rd_fls_snr(:),'callback',{@wgr_fls_snr_call,E});
else %fls
    set(E.rd_tvmodel(2),'position',[0.1 0.1 0.8 0.45]);
    set(E.rd_tvmodel(1),'position',[0.1 0.55 0.8 0.45]);
    set([E.tx_rd11_tvmodel(:),E.ed_rd11_tvmodel(:)],'visible','off');
    set(E.tx_slw(:),'visible','off');
    set(E.bg_slw_conn,'visible','off');
    set([E.tx_fls_para],'visible','on');
    set(E.rd_slw(:),'visible','off');
    set(E.rd_slw(:),'value',0);
    set(E.rd_fls_snr(:),'visible','on'); 
    flag_auto_fix = cell2mat(get(E.rd_fls_snr(:),'value'));
    if ~sum(flag_auto_fix)
        set(E.rd_fls_snr(2),'value',1);
        set(E.tx_fls_snr(2),'visible','on'); 
    end
    set(E.rd_fls_snr(:),'callback',{@wgr_fls_snr_call,E});
    
end


function []=ROIwise_call(varargin)
E = varargin{3};
R1 = cell2mat(get(E.rd_rvw,'val'));
R2 = cell2mat(get(E.rd_mr,'val'));
R = cell2mat(get(E.rd_tvmodel,'val'));  % Get state of radios.

if sum(R1([1 3]))
    if ~sum(R2(1:2))
        set(E.rd_mr(1),'val',1);
    end
    if R1(1)
        set(E.bg_seed_voxel,'visible','on');
        set(E.bg_seed_ROI,'visible','on');
    else%if R1(3)
        set(E.bg_seed_voxel,'visible','off');
        set(E.bg_seed_ROI,'visible','off');
    end
    set([E.tx_mr(1),E.tx_mask],'string','Mask');
    set(E.rd_mr(1:2),'visible','on');
    set(E.rd_mr(3:5),'visible','off');
else
    if sum(R2(1:2))
        set(E.rd_mr(4),'val',1);
    end   
    set(E.bg_seed_voxel,'visible','off');
    set(E.bg_seed_ROI,'visible','off');
    set([E.tx_mr(1),E.tx_mask],'string','ROI');
    set(E.rd_mr(1:2),'visible','off');
    set(E.rd_mr(3:5),'visible','on');    
end    

if sum(R1(1:2))
    set([E.rd_slw_conn(:);E.ed_slw_pvalue(1)],'enable','off')
    set(E.ed_slw_pvalue(1),'str','no');
else
    set([E.rd_slw_conn(:);E.ed_slw_pvalue(1)],'enable','on')
    set(E.ed_slw_pvalue(1),'str','0.001');
end
mask_datadir_mat_call([],[],E);


function []=mask_datadir_mat_call(varargin)
E = varargin{3};
R2 = cell2mat(get(E.rd_mr,'val'));
R3 = R2(5);
if R3
    set(E.ed_mat,'visible','on');
else
    set(E.ed_mat,'visible','off');
end
if R2(1)
    set(E.tx_mask,'enable','off');
    set(E.pb_mask_dir,'enable','off');
    set(E.ed_mrs,'enable','off');
    set(E.ed_mrs,'str','reslice ./spm/apriori/brainmask.nii');
else
    set(E.tx_mask,'enable','on');
    set(E.pb_mask_dir,'enable','on');
    set(E.ed_mrs,'enable','on');
    set(E.ed_mrs,'str','not selected');
end

if sum(R2(4:5))
    set(E.tx_mrs,'enable','off');
    set(E.ed_bg_data_dir,'enable','off');
    set(E.pb_datadir,'enable','off');
    set(E.ed_bg_data_dir,'str','select files in above line');
else
    set(E.tx_mrs,'enable','on');
    set(E.ed_bg_data_dir,'enable','on');
    set(E.pb_datadir,'enable','on');
    set(E.ed_bg_data_dir,'str','not selected');
end

function [] = wgr_fls_snr_call(varargin)
E = varargin{3};
flag_auto_fix = cell2mat(get(E.rd_fls_snr(:),'value'));
if ~sum(flag_auto_fix) | flag_auto_fix(2)
    set(E.rd_fls_snr(2),'value',1);
    set(E.rd_fls_snr(1),'value',0);
    set(E.tx_fls_snr(2),'visible','on'); 
    set(E.tx_fls_snr(1),'visible','off');      
elseif flag_auto_fix(1)
    set(E.tx_fls_snr(1),'visible','on'); 
    set(E.rd_fls_snr(1),'value',1);
    set(E.tx_fls_snr(2),'visible','off');      
    set(E.rd_fls_snr(2),'value',0);
end


function [] = wgr_select_dir(varargin)
E = varargin{3};
str = varargin{4};
io = varargin{5};
if strcmp(io ,'in')
    data_dir = spm_select(inf,str);
    set(E.ed_bg_data_dir,'string',data_dir);
elseif strcmp(io ,'out')
    data_dir = spm_select(inf,str);
    set(E.ed_bg_dir_out,'string',data_dir);
else
    files = spm_select(inf,str);
    set(E.ed_mrs_files,'string',files);    
    num = size(files,1);
    data_dir=[]; data_dir2=[];
    for i=1:num
        fname = strcat(files(i,:));
        [pathstr, name, ext] = fileparts(fname);
        if i==1
            data_dir = [data_dir,fname];
            data_dir2 = [data_dir2,name];
        else
            data_dir = [data_dir,'; ',fname];
            data_dir2 = [data_dir2,'; ',name];
        end
    end
    set(E.ed_mrs,'string',data_dir);
    set(E.tx_mask,'TooltipString',data_dir2);
end

function [] = wgr_reset(varargin)
E = varargin{3};
set(E.ed_bg_data_dir,'string','not selected');
set(E.ed_bg_dir_out,'string','not selected');
set(E.ed_mrs,'string','not selected');
set(E.ed_prefix,'string','');
set(E.ed_par,'string','');

function [] = wgr_run_all(varargin)
E = varargin{3};
F.E = E;
if E.fc_ec(1)
    fc_ec = 'Dynamic Functional Connectivity';
elseif E.fc_ec(2)
    fc_ec = 'Dynamic Effective Connectivity';
end
try
    delete(E.S.fig);
end

%% parllel workers
par_num = str2num(get(E.ed_par(1),'string'));
mps = matlabpool('size');
if par_num
    loc_DBC = ['local_DBC',num2str(par_num)];
    if par_num~=mps
        try 
            myCluster = parcluster('local');
            myCluster.NumWorkers = par_num; 
            saveAsProfile(myCluster,loc_DBC); 
            matlabpool('open',loc_DBC,par_num);
        catch
            try
                matlabpool('open',loc_DBC,par_num);
            catch
                try
                    delete(gcp)
                    matlabpool('open',loc_DBC,par_num);
                catch
                    matlabpool close
                    matlabpool('open',loc_DBC,par_num);
                end
            end
%             fprintf('parallel computation setting failed \n', mps);
        end
    end
end
mps = matlabpool('size');
fprintf('Now DynamicBC is running on %d workers.\n', mps);

work_dir = get(E.ed_bg_data_dir,'string');
numlim = 40;
num0 = length(work_dir);
if num0>numlim;
    work_dir2 = [];
    num_bin = ceil(num0./numlim);
    for i=1:num_bin
        if i~=num_bin
            ind0 = [(i-1)*numlim+1] : i*numlim;
        else
            ind0 = [(i-1)*numlim+1] : num0;
        end        
        work_dir2 = [work_dir2  work_dir(ind0) ' '];
    end
else
    work_dir2 = work_dir;
end
    
tvmodel_id = cell2mat(get(E.rd_tvmodel,'val'));
tvmodel_id = find(tvmodel_id>0);
tvmodel = get(E.rd_tvmodel(tvmodel_id),'string');
if tvmodel_id==2 % fls
    fls_snr_id = find(cell2mat(get(E.rd_fls_snr,'val'))>0);
    fls_snr_str = get(E.rd_fls_snr(fls_snr_id),'string');
    fls_snr = get(E.tx_fls_snr(fls_snr_id),'string');
    slw_fls_str = ['SNR:',fls_snr_str, '(', fls_snr,')'];
elseif tvmodel_id==1 % sliding windows
    slw_id = find(cell2mat(get(E.rd_slw,'val'))>0);
    slw_alignment = get(E.rd_slw(slw_id),'string');
    slw_winsize_str = get(E.tx_rd11_tvmodel(1),'string');
    slw_winsize = get(E.ed_rd11_tvmodel(1),'string');
    slw_overlap_str = get(E.tx_rd11_tvmodel(2),'string');
    slw_overlapsize = get(E.ed_rd11_tvmodel(2),'string');
    slw_order_str = get(E.tx_rd11_tvmodel(3),'string');
    slw_order = get(E.ed_rd11_tvmodel(3),'string');
    slw_fls_str = [slw_alignment,'; ',slw_winsize_str,slw_winsize,...
        '; ',slw_overlap_str,slw_overlapsize];
    if E.fc_ec(2)
        slw_fls_str = [slw_fls_str,'; ',slw_order_str,slw_order];
    end
end
rd_rvw_id = cell2mat(get(E.rd_rvw,'val'));
set_roi = get(E.rd_rvw(find(rd_rvw_id>0)),'string');
mask_roi = get(E.ed_mrs,'string');
out_dir = get(E.ed_bg_dir_out,'string');
num0 = length(out_dir);
if num0>numlim;
    out_dir2 = [];
    num_bin = ceil(num0./numlim);
    for i=1:num_bin
        if i~=num_bin
            ind0 = [(i-1)*numlim+1] : i*numlim;
        else
            ind0 = [(i-1)*numlim+1] : num0;
        end        
        out_dir2 = [out_dir2  out_dir(ind0) ' '];
    end
else
    out_dir2 = out_dir;
end
    
prefix_name = get(E.ed_prefix(1),'string');
% log_name = get(E.ed_log_name(1),'string');
mat_flag = get(E.rd_mr(5),'val');
if mat_flag
    mat_name = ['<FONT color="blue">---variable_name:',get(E.ed_mat(1),'string')];
else
    mat_name='';
end
par_num = get(E.ed_par(1),'string');
str_run = 'Finish editing the configuration parameters?';
mytext = ['<html><body><table border="1">' ...
          '<tr><th><FONT color="red" size="+1.5" face="Comic Sans MS">Check Parameters Settings</font></th></tr>' ...
          ['<tr><td><center>',fc_ec,'</td></tr>'] ...
          '<tr><th>Working Directory</th></tr>' ...
          ['<tr><td><center>',work_dir2,'</td></tr>'] ...
          ['<tr><th>TV model: <FONT color="blue">',tvmodel,'</th></tr>'] ...
          ['<tr><td><center>',slw_fls_str,'</td></tr>'] ...
          ['<tr><th>Set ROI: <FONT color="blue">',set_roi,'</th></tr>'] ...
          ['<tr><th>Mask/ROI',mat_name,'</th></tr>'] ...
          ['<tr><td><center>',mask_roi,'</td></tr>'] ...
          '<tr><th>Output Directory</th></tr>' ...
          ['<tr><td><center>',out_dir2,'</td></tr>'] ...
          ['<tr><td><center>Prefix:<FONT color="blue">',prefix_name,' <FONT color="black">; Parallel_workers:<FONT color="blue">',par_num,'</td></tr>'] ...Logfile:<FONT color="blue">',log_name,' <FONT color="black">; 
          ['<tr><FONT color="red" size="+0.5" face="Comic Sans MS">',str_run,'</font></tr>'] ...
          '</table></body></html>'
          ];
if strcmpi(strcat(work_dir),strcat(out_dir));
    error('DynamicBC error: The data directory is same with output directory, Please change the output directory!')
end      
F.hfig = figure('name',['Configurations Checking(',getenv('USERNAME'),')'],...
              'Visible','on',...
              'numbertitle','off',...
              'menubar','none',...              'units','normalized',...
              'color','w',...              'position',[0.3 0.3 0.265 0.65]);   
              'position',[150  150  320  600]);
je = javax.swing.JEditorPane('text/html', mytext);
jp = javax.swing.JScrollPane(je);
[hcomponent, hcontainer] = javacomponent(jp, [], F.hfig);
set(hcontainer, 'units', 'normalized', 'position', [0,0,1,1]);
movegui(F.hfig,'center');

F.pb_run_check(1) = uicontrol(F.hfig,...
                    'style','pushbutton',...
                    'units','normalized',...
                    'position',[0.6 0.02 0.35 0.08],...
                    'string','Yes&Run',...       
                    'fontweight','bold',...
                    'fontname','Comic Sans MS',...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'foregroundcolor',[0 0 .8],...
                    'backgroundc',get(F.hfig,'color'),...
                    'value',0,...
                    'TooltipString','yes and run it');
F.pb_run_check(2) = uicontrol(F.hfig,...
                    'style','pushbutton',...
                    'units','normalized',...
                    'position',[0.05 0.02 0.4 0.08],...
                    'string','No&return',...       
                    'fontweight','bold',...
                    'fontname','Comic Sans MS',...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'foregroundcolor',[0 0 .8],...
                    'backgroundc',get(F.hfig,'color'),...
                    'value',0,...
                    'TooltipString','no and please change it'); 
F.pb_run_check(3) = uicontrol(F.hfig,...
                    'style','pushbutton',...
                    'units','normalized',...
                    'position',get(F.pb_run_check(2),'position'),...
                    'string','Unlock Run',...       
                    'fontweight','bold',...
                    'fontname','Comic Sans MS',...
                    'fontunits', 'normalized', 'fontsize',0.4,...
                    'foregroundcolor',[0 0 .8],...
                    'backgroundc',get(F.hfig,'color'),...
                    'value',0,...
                    'Visible','off',...
                    'TooltipString','stop!');                   
                
set(F.pb_run_check(:),'callback',{@wgr_run_check,F});

function [] = wgr_run_check(varargin)
F = varargin{3};
flag = find(cell2mat(get(F.pb_run_check(:),'val'))>0);
if flag==2
    delete(F.hfig);
elseif flag==1
    disp('Running now!')    
    set(F.pb_run_check(1),'Visible','on');
    set(F.pb_run_check(3),'Visible','on');
    set(F.pb_run_check(1),'backgroundc',[0.75 0 0.75]);
    set(F.pb_run_check(1),'Enable', 'off');
    movegui(F.hfig,'east');
    DynamicBC_run(F)
elseif flag==3
    fprintf('Unlock successful!\n')
    set(F.pb_run_check(1),'Visible','on');
    set(F.pb_run_check(1),'Enable', 'on');
    set(F.pb_run_check(2),'Visible','on');
    set(F.pb_run_check(3),'Visible','off');
    set(F.pb_run_check(1),'backgroundc',get(F.hfig,'color')); 
    movegui(F.hfig,'center');
end